[package]
name = "phase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "phase"
path = "examples/phase/phase.rs"

[dependencies]
libm = "0.2.8"
plotters = "0.3.5"
